# Generated by Django 3.2.19 on 2023-06-07 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите ваше имя', max_length=100)),
                ('last_name', models.CharField(help_text='Введите вашу фамилию', max_length=100)),
                ('avatar', models.ImageField(default='avatars/default.jpg', help_text='Загрузите фотографию с вами', upload_to='avatars')),
                ('email', models.EmailField(help_text='Введите вашу почту', max_length=255, unique=True, verbose_name='email address')),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women')], default='M', help_text='Выберите ваш пол', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
